-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-13 16:08:53 GMT+08:00
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



SET ECHO ON
SPOOL mau_schema_output.txt

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE artwork_style CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibition CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE purchase CASCADE CONSTRAINTS;

DROP TABLE statu CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code      NUMBER(4) NOT NULL,
    artist_name      VARCHAR2(50) NOT NULL,
    artist_address   VARCHAR2(50) NOT NULL,
    artist_phone     NUMBER(10)
);

COMMENT ON COLUMN artist.artist_code IS
    'artist_code';

COMMENT ON COLUMN artist.artist_name IS
    'artist_name';

COMMENT ON COLUMN artist.artist_address IS
    'artist_address';

COMMENT ON COLUMN artist.artist_phone IS
    'artist_phone';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    artwork_no         NUMBER(3) NOT NULL,
    artist_code        NUMBER(4) NOT NULL,
    artwork_title      VARCHAR2(30) NOT NULL,
    dae_accepted       DATE NOT NULL,
    artwork_minprice   NUMBER(10) NOT NULL,
    artwork_media      VARCHAR2(20) NOT NULL,
    gallery_id         NUMBER(3) NOT NULL
);

ALTER TABLE artwork ADD CHECK ( artwork_minprice BETWEEN 1000 AND 1000000 );

COMMENT ON COLUMN artwork.artwork_no IS
    'artwork_no';

COMMENT ON COLUMN artwork.artist_code IS
    'artist_code';

COMMENT ON COLUMN artwork.artwork_title IS
    'artwork_title';

COMMENT ON COLUMN artwork.dae_accepted IS
    'dae_accepted';

COMMENT ON COLUMN artwork.artwork_minprice IS
    'artwork_minprice';

COMMENT ON COLUMN artwork.artwork_media IS
    'artwork_media';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_no,
                                                            artist_code );

CREATE TABLE artwork_style (
    artwork_style   VARCHAR2(30) NOT NULL,
    parent_style    VARCHAR2(30),
    artwork_no      NUMBER(3) NOT NULL,
    artist_code     NUMBER(4) NOT NULL
);

COMMENT ON COLUMN artwork_style.artwork_style IS
    'artwork_style';

COMMENT ON COLUMN artwork_style.parent_style IS
    'parent_style';

COMMENT ON COLUMN artwork_style.artwork_no IS
    'artwork_no';

COMMENT ON COLUMN artwork_style.artist_code IS
    'artist_code';

ALTER TABLE artwork_style
    ADD CONSTRAINT artwork_style_pk PRIMARY KEY ( artwork_style,
                                                  artwork_no,
                                                  artist_code );

CREATE TABLE customer (
    cust_id         NUMBER(8) NOT NULL,
    cust_name       VARCHAR2(50) NOT NULL,
    cust_address    VARCHAR2(50) NOT NULL,
    cust_phone      VARCHAR2(50) NOT NULL,
    cust_business   VARCHAR2(50)
);

COMMENT ON COLUMN customer.cust_id IS
    'cust_id';

COMMENT ON COLUMN customer.cust_name IS
    'cust_name';

COMMENT ON COLUMN customer.cust_address IS
    'cust_address';

COMMENT ON COLUMN customer.cust_phone IS
    'cust_phone';

COMMENT ON COLUMN customer.cust_business IS
    'cust_business';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE exhibition (
    exb_id               NUMBER(7) NOT NULL,
    exb_start_date       DATE NOT NULL,
    exb_end_date         DATE NOT NULL,
    feature_in_catalog   VARCHAR2(5) NOT NULL,
    artwork_no           NUMBER(3) NOT NULL,
    artist_code          NUMBER(4) NOT NULL,
    gallery_id           NUMBER(3) NOT NULL
);

COMMENT ON COLUMN exhibition.exb_id IS
    'surrogate key';

COMMENT ON COLUMN exhibition.exb_start_date IS
    'exb_start_date';

COMMENT ON COLUMN exhibition.exb_end_date IS
    'exb_end_date';

COMMENT ON COLUMN exhibition.feature_in_catalog IS
    'feature_in_catalog';

COMMENT ON COLUMN exhibition.artwork_no IS
    'artwork_no';

COMMENT ON COLUMN exhibition.artist_code IS
    'artist_code';

ALTER TABLE exhibition ADD CONSTRAINT exhibition_pk PRIMARY KEY ( exb_id );

ALTER TABLE exhibition
    ADD CONSTRAINT nk_exb UNIQUE ( artwork_no,
                                   artist_code,
                                   gallery_id );

CREATE TABLE gallery (
    gallery_id               NUMBER(3) NOT NULL,
    gallery_name             VARCHAR2(30) NOT NULL,
    gallery_manager          VARCHAR2(50) NOT NULL,
    gallery_phone            NUMBER(10) NOT NULL,
    gallery_charge_percent   NUMBER(2) NOT NULL,
    gallery_street           VARCHAR2(30) NOT NULL,
    gallery_town             VARCHAR2(30) NOT NULL,
    gallery_state            VARCHAR2(30) NOT NULL,
    gallery_open             DATE NOT NULL,
    gallery_close            DATE NOT NULL
);

ALTER TABLE gallery ADD CHECK ( gallery_charge_percent BETWEEN 0 AND 1 );

COMMENT ON COLUMN gallery.gallery_name IS
    'gallery_name';

COMMENT ON COLUMN gallery.gallery_manager IS
    'gallery_manager';

COMMENT ON COLUMN gallery.gallery_phone IS
    'gallery_phone';

COMMENT ON COLUMN gallery.gallery_charge_percent IS
    'gallery_charge_percent';

COMMENT ON COLUMN gallery.gallery_street IS
    'gallery_street';

COMMENT ON COLUMN gallery.gallery_town IS
    'gallery_town';

COMMENT ON COLUMN gallery.gallery_state IS
    'gallery_state';

COMMENT ON COLUMN gallery.gallery_open IS
    'gallery_open';

COMMENT ON COLUMN gallery.gallery_close IS
    'gallery_close';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE purchase (
    sale_id        NUMBER(8) NOT NULL,
    date_of_sale   DATE NOT NULL,
    sale_price     NUMBER(8) NOT NULL,
    cust_id        NUMBER(8) NOT NULL,
    exb_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN purchase.sale_id IS
    'sale_id';

COMMENT ON COLUMN purchase.date_of_sale IS
    'date_of_sale';

COMMENT ON COLUMN purchase.cust_id IS
    'cust_id';

COMMENT ON COLUMN purchase.exb_id IS
    'surrogate key';

ALTER TABLE purchase ADD CONSTRAINT purchase_pk PRIMARY KEY ( sale_id );

CREATE TABLE statu (
    statu_id      NUMBER(3) NOT NULL,
    statu_date    DATE NOT NULL,
    statu_type    VARCHAR2(30) NOT NULL,
    artwork_no    NUMBER(3) NOT NULL,
    artist_code   NUMBER(4) NOT NULL,
    gallery_id    NUMBER(3) NOT NULL
);

COMMENT ON COLUMN statu.statu_id IS
    'surrogate key';

COMMENT ON COLUMN statu.statu_date IS
    'statu_date';

COMMENT ON COLUMN statu.statu_type IS
    'statu_type';

COMMENT ON COLUMN statu.artwork_no IS
    'artwork_no';

COMMENT ON COLUMN statu.artist_code IS
    'artist_code';

ALTER TABLE statu ADD CONSTRAINT statu_pk PRIMARY KEY ( statu_id );

ALTER TABLE statu
    ADD CONSTRAINT nk_statu UNIQUE ( artwork_no,
                                     artist_code,
                                     gallery_id );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE exhibition
    ADD CONSTRAINT artwork_exb FOREIGN KEY ( artwork_no,
                                             artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE statu
    ADD CONSTRAINT artwork_statu FOREIGN KEY ( artwork_no,
                                               artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE artwork_style
    ADD CONSTRAINT artwork_style FOREIGN KEY ( artwork_no,
                                               artist_code )
        REFERENCES artwork ( artwork_no,
                             artist_code );

ALTER TABLE purchase
    ADD CONSTRAINT customer_purchase FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE purchase
    ADD CONSTRAINT exb_purchase FOREIGN KEY ( exb_id )
        REFERENCES exhibition ( exb_id );

ALTER TABLE artwork
    ADD CONSTRAINT gallery_artwork FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE exhibition
    ADD CONSTRAINT gallery_exb FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE statu
    ADD CONSTRAINT gallery_statu FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL OFF
SET ECHO OFF
