
/**
 * This is the Koala class.
 *
 * @06-07-2020
 */
public class Koala
{
    private int age; // from 1 - 18, generated by RandomNumber
    private boolean isHealthy; // T = Healthy, F = injured

    /**
     * Default Constructor for objects of class Koala
     */
    public Koala()
    {
        // initialise instance variables
        setIsHealthy(true);
        setAge(0);
    }
    
    /**
     * Parametered Constructor for objects of class Koala
     */
    public Koala(boolean health, int ageNumber)
    {
        // pass the values to the variables
        setIsHealthy(health);
        setAge(ageNumber);
    }
    
    /**
     * Method getAge
     *
     * return a int number of age
     */
    public int getAge()
    {
        return age;
    }

    /**
     * Method getIsHealthy
     *
     * return a boolean value of healthy or not
     */
    public boolean getIsHealthy()
    {
        return isHealthy;
    }
    
    /**
     * Method setAge
     *
     * set the Koala's age
     */
    public void setAge(int ageNumber)
    {
        age = ageNumber;
    }
    
    /**
     * Method setIsHealthy
     *
     * set the condition for this Koala
     */
    public void setIsHealthy(boolean health)
    {
        isHealthy = health;
    }
}
